"""new fields in user model

Revision ID: 290f456dabb4
Revises: b3f501a33ae2
Create Date: 2019-03-13 09:55:48.259342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290f456dabb4'
down_revision = 'b3f501a33ae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
